[build]
  command = "npx prisma generate && npm run build"
  publish = "out"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions."getDocs"]
  external_node_modules = ["@prisma/client", "@prisma/adapter-neon"]
